# Generated by Django 2.2.7 on 2019-11-25 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_auto_20191125_1403"),
        ("homex", "0002_auto_20191125_1359"),
    ]

    operations = [
        migrations.AddField(
            model_name="xxx",
            name="r4",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="xxx_r4",
                to="home.R6",
            ),
        ),
    ]
