# Generated by Django 2.2.7 on 2019-11-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_r3'),
    ]

    operations = [
        migrations.CreateModel(
            name='R4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r1', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='R6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r2', models.BigIntegerField()),
            ],
        ),
    ]
