# Generated by Django 2.2.7 on 2019-11-21 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_r4_r6"),
    ]

    operations = [
        migrations.RemoveField(model_name="r2", name="r2",),
    ]
