# Generated by Django 2.2.7 on 2019-12-04 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_tgggg_r2"),
    ]

    operations = [
        migrations.AddField(
            model_name="r4",
            name="r5",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="r4_r5",
                to="home.TGGGG",
            ),
        ),
    ]
