# Generated by Django 2.2.7 on 2019-12-04 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_bvvvv_r2"),
    ]

    operations = [
        migrations.AddField(
            model_name="gffff",
            name="r2",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gffff_r2",
                to="home.R1",
            ),
        ),
    ]
