# Generated by Django 2.2.7 on 2019-12-04 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_gggg_r3'),
    ]

    operations = [
        migrations.AddField(
            model_name='gggg',
            name='r4',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gggg_r4', to='home.R2'),
        ),
    ]
